### ISSUE TITLE
Labaling fails when Connectivity = Eight_connecteness 

### ISSUE THREAD

**Issue by pbajcsy** [usnistgov/WIPP-mask-labeling-plugin#5]
When connectivity is selected to be  "EIGHT_CONNECTEDNESS" from the web UI, the labeling fails with the following error:

Apr 05, 2021 1:29:10 AM gov.nist.itl.ssd.wipp.masklabelingplugin.Main main
SEVERE: Error while labeling the image.
java.lang.IllegalArgumentException: No enum constant gov.nist.itl.ssd.wipp.masklabelingplugin.utils.Connectedness.EIGHT_CONNECTED
        at java.lang.Enum.valueOf(Enum.java:238)
        at gov.nist.itl.ssd.wipp.masklabelingplugin.utils.Connectedness.valueOf(Connectedness.java:3)
        at gov.nist.itl.ssd.wipp.masklabelingplugin.Main.main(Main.java:69)

**Comment by MyleneSimon** [comment]
This issue has been fixed in 0.0.2.
